ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8

# Python und Abhängigkeiten installieren
RUN apk add --no-cache \
    python3 \
    py3-pip \
    jq \
    bash \
    && pip3 install --no-cache-dir --break-system-packages \
    pyserial \
    paho-mqtt

# Arbeitsverzeichnis
WORKDIR /app

# Skripte kopieren
COPY run.sh /app/
COPY usb-esi3.py /app/
COPY requirements.txt /app/

# Ausführbar machen
RUN chmod a+x /app/run.sh

CMD [ "/app/run.sh" ]
